# Generated by Django 5.1.1 on 2024-09-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Изображение')),
                ('heading', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subheading', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('whatsapp_link', models.URLField(verbose_name='Ссылка на WhatsApp')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('rating_text', models.CharField(max_length=100, verbose_name='Текст рейтинга')),
            ],
            options={
                'verbose_name': 'Геройский раздел',
                'verbose_name_plural': 'Геройские разделы',
            },
        ),
    ]
