# Generated by Django 5.1.1 on 2024-09-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_contactinfo_delete_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
