# Generated by Django 5.1.1 on 2024-09-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_contactinfo_phone_number_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone_number_en',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone_number_ru',
        ),
    ]
