# Generated by Django 5.1.1 on 2024-09-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_contactinfo_phone_number_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='phone_link',
            field=models.CharField(blank=True, help_text='Введите номер в формате: +971XXXXXXX', max_length=30, null=True, verbose_name='Телефонная ссылка'),
        ),
    ]
