# Generated by Django 5.1.1 on 2024-09-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_contactinfo_phone_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='opening_days',
            field=models.CharField(blank=True, help_text='Например: пн-сб: 10:00–20:00 вс: ЗАКРЫТО', max_length=100, null=True, verbose_name='Дни работы'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_time_title',
            field=models.CharField(blank=True, help_text='Например: Время открытия', max_length=100, null=True, verbose_name='Заголовок время открытия'),
        ),
    ]
