# Generated by Django 5.1.1 on 2024-09-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_contactinfo_opening_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='opening_days_en',
            field=models.CharField(blank=True, help_text='Например: пн-сб: 10:00–20:00 вс: ЗАКРЫТО', max_length=100, null=True, verbose_name='Дни работы'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_days_ru',
            field=models.CharField(blank=True, help_text='Например: пн-сб: 10:00–20:00 вс: ЗАКРЫТО', max_length=100, null=True, verbose_name='Дни работы'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_time_title_en',
            field=models.CharField(blank=True, help_text='Например: Время открытия', max_length=100, null=True, verbose_name='Заголовок время открытия'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_time_title_ru',
            field=models.CharField(blank=True, help_text='Например: Время открытия', max_length=100, null=True, verbose_name='Заголовок время открытия'),
        ),
    ]
