# Generated by Django 5.1.1 on 2024-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_contactinfo_opening_days_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='Главная', max_length=100, verbose_name='Главная')),
                ('services', models.CharField(default='Услуги', max_length=100, verbose_name='Услуги')),
                ('about_us', models.CharField(default='О нас', max_length=100, verbose_name='О нас')),
                ('contacts', models.CharField(default='Контакты', max_length=100, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Навигационная ссылка',
                'verbose_name_plural': 'Навигационные ссылки',
            },
        ),
    ]
