# Generated by Django 5.1.1 on 2024-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_navigationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='about_us_en',
            field=models.CharField(default='О нас', max_length=100, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='about_us_ru',
            field=models.CharField(default='О нас', max_length=100, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='contacts_en',
            field=models.CharField(default='Контакты', max_length=100, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='contacts_ru',
            field=models.CharField(default='Контакты', max_length=100, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='home_en',
            field=models.CharField(default='Главная', max_length=100, null=True, verbose_name='Главная'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='home_ru',
            field=models.CharField(default='Главная', max_length=100, null=True, verbose_name='Главная'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='services_en',
            field=models.CharField(default='Услуги', max_length=100, null=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='services_ru',
            field=models.CharField(default='Услуги', max_length=100, null=True, verbose_name='Услуги'),
        ),
    ]
