# Generated by Django 5.1.1 on 2024-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_navigationlink_about_us_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_type', models.CharField(choices=[('image', 'Картинка'), ('video', 'Видео')], default='image', max_length=5, verbose_name='Тип слайда')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/images/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='slides/videos/', verbose_name='Видео')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок 1')),
                ('subtitle2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок 2')),
                ('cta_whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('cta_call', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонный номер для вызова')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('google_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Рейтинг Google')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
            ],
            options={
                'verbose_name': 'Слайд героя',
                'verbose_name_plural': 'Слайды героя',
            },
        ),
    ]
