# Generated by Django 5.1.1 on 2024-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_heroslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='google_rating',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='reviews_count',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='rating_and_reviews',
            field=models.CharField(blank=True, help_text='Например: Rated 4.9 with 34 reviews', max_length=100, null=True, verbose_name='Рейтинг и отзывы'),
        ),
    ]
