# Generated by Django 5.1.1 on 2024-09-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_heroslide_options_remove_heroslide_cta_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='icon1',
            field=models.FileField(blank=True, help_text='Загрузите первую иконку (например, SVG файл)', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 1'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon2',
            field=models.FileField(blank=True, help_text='Загрузите вторую иконку (например, SVG файл)', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 2'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon3',
            field=models.FileField(blank=True, help_text='Загрузите третью иконку (например, SVG файл)', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 3'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon4',
            field=models.FileField(blank=True, help_text='Загрузите четвертую иконку (например, SVG файл)', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 4'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon5',
            field=models.FileField(blank=True, help_text='Загрузите пятую иконку (например, SVG файл)', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 5'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='text1',
            field=models.CharField(blank=True, help_text='Текст преимущества для первой иконки, например "Professional team"', max_length=100, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='text2',
            field=models.CharField(blank=True, help_text='Текст преимущества для второй иконки, например "All problems solvers"', max_length=100, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='text3',
            field=models.CharField(blank=True, help_text='Текст преимущества для третьей иконки, например "Fast delivery"', max_length=100, null=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='text4',
            field=models.CharField(blank=True, help_text='Текст преимущества для четвертой иконки, например "Quality is our aim"', max_length=100, null=True, verbose_name='Текст 4'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='text5',
            field=models.CharField(blank=True, help_text='Текст преимущества для пятой иконки, например "Более 7 лет на рынке"', max_length=100, null=True, verbose_name='Текст 5'),
        ),
    ]
