# Generated by Django 5.1.1 on 2024-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_heroslide_icon2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='icon1',
            field=models.ImageField(blank=True, help_text='Загрузите первую иконку (например, SVG файл)', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 1'),
        ),
    ]
