# Generated by Django 5.1.1 on 2024-09-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_heroslide_icon1_alter_heroslide_icon2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='icon1',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon2',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon3',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon4',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon5',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='text5',
        ),
        migrations.CreateModel(
            name='IconText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(help_text='Загрузите SVG иконку или изображение', upload_to='hero_slider/icons/', verbose_name='Иконка')),
                ('text', models.CharField(help_text='Текст, связанный с иконкой, например, "Professional team"', max_length=255, verbose_name='Текст')),
                ('hero_slide', models.ForeignKey(help_text='Связанный слайд', on_delete=django.db.models.deletion.CASCADE, related_name='icon_texts', to='service.heroslide', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': 'Иконка и текст',
                'verbose_name_plural': 'Иконки и тексты',
            },
        ),
    ]
