# Generated by Django 5.1.1 on 2024-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_heroslide_icon1_remove_heroslide_icon2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='icon1',
            field=models.FileField(blank=True, help_text='Загрузите файл иконки 1', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 1'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon1_text',
            field=models.CharField(blank=True, help_text='Например, "Professional team"', max_length=100, null=True, verbose_name='Текст для иконки 1'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon2',
            field=models.FileField(blank=True, help_text='Загрузите файл иконки 2', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 2'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon2_text',
            field=models.CharField(blank=True, help_text='Например, "All problems solvers"', max_length=100, null=True, verbose_name='Текст для иконки 2'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon3',
            field=models.FileField(blank=True, help_text='Загрузите файл иконки 3', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 3'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon3_text',
            field=models.CharField(blank=True, help_text='Например, "Fast delivery"', max_length=100, null=True, verbose_name='Текст для иконки 3'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon4',
            field=models.FileField(blank=True, help_text='Загрузите файл иконки 4', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 4'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon4_text',
            field=models.CharField(blank=True, help_text='Например, "Quality is our aim"', max_length=100, null=True, verbose_name='Текст для иконки 4'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon5',
            field=models.FileField(blank=True, help_text='Загрузите файл иконки 5', null=True, upload_to='hero_slider/icons/', verbose_name='Иконка 5'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='icon5_text',
            field=models.CharField(blank=True, help_text='Например, "Более 7 лет на рынке"', max_length=100, null=True, verbose_name='Текст для иконки 5'),
        ),
        migrations.DeleteModel(
            name='IconText',
        ),
    ]
