# Generated by Django 5.1.1 on 2024-09-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_heroslide_icon1_heroslide_icon1_text_heroslide_icon2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='icon1',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon1_text',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon2',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon2_text',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon3',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon3_text',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon4',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon4_text',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon5',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='icon5_text',
        ),
    ]
