# Generated by Django 5.1.1 on 2024-09-29 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_remove_heroslide_icon1_remove_heroslide_icon1_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageIconText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(help_text='Загрузите SVG или PNG файл для иконки', upload_to='advantage_icons/', verbose_name='Иконка')),
                ('text', models.CharField(help_text='Текст преимущества, например, "Professional team"', max_length=255, verbose_name='Текст преимущества')),
                ('hero_slide', models.ForeignKey(help_text='Слайд, к которому относится данное преимущество', on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='service.heroslide', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
