# Generated by Django 5.1.1 on 2024-09-30 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_advantageicontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок, который отображается над сеткой с изображениями', max_length=255, verbose_name='Заголовок секции')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение для элемента', upload_to='features_images/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Название, отображаемое под изображением', max_length=100, verbose_name='Название элемента')),
                ('link', models.URLField(help_text='URL для ссылки, которая будет прикреплена к элементу', verbose_name='Ссылка для элемента')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='service.featuressection', verbose_name='Секция')),
            ],
        ),
    ]
