# Generated by Django 5.1.1 on 2024-09-30 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_featuressection_featureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
            ],
        ),
        migrations.AlterModelOptions(
            name='featuressection',
            options={'verbose_name': 'Раздел техника', 'verbose_name_plural': 'Раздел техники'},
        ),
        migrations.CreateModel(
            name='ServiceTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок таба')),
                ('tab_id', models.CharField(max_length=100, verbose_name='ID таба (для переключения)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный по умолчанию')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='service.servicessection', verbose_name='Секция')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('image', models.ImageField(upload_to='service_images/', verbose_name='Изображение')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.servicetab', verbose_name='Таб')),
            ],
        ),
    ]
