# Generated by Django 5.1.1 on 2024-09-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_servicessection_alter_featuressection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetab',
            name='is_active',
        ),
    ]
