# Generated by Django 5.1.1 on 2024-09-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_remove_servicetab_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetab',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный по умолчанию'),
        ),
    ]
