# Generated by Django 5.1.1 on 2024-09-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_servicetab_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='image',
        ),
        migrations.AddField(
            model_name='servicetab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Изображение таба'),
        ),
    ]
