# Generated by Django 5.1.1 on 2024-09-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_remove_serviceitem_image_servicetab_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание баннера')),
            ],
            options={
                'verbose_name': 'Раздел баннер',
                'verbose_name_plural': 'Раздел баннера',
            },
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'Пункт для кнопки', 'verbose_name_plural': 'Пункты для кнопки'},
        ),
        migrations.AlterModelOptions(
            name='servicessection',
            options={'verbose_name': 'Раздел услуга', 'verbose_name_plural': 'Раздел услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicetab',
            options={'verbose_name': 'Кнопка для услуги', 'verbose_name_plural': 'Кнопки для услуг'},
        ),
    ]
