# Generated by Django 5.1.1 on 2024-09-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_bannersection_alter_serviceitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': "Секция 'Почему стоит выбрать нас?'",
                'verbose_name_plural': "Секции 'Почему стоит выбрать нас?'",
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок преимущества')),
                ('description', models.TextField(verbose_name='Описание преимущества')),
                ('image', models.ImageField(upload_to='advantage_images/', verbose_name='Изображение преимущества')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='service.whychooseussection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимуществa',
            },
        ),
    ]
