# Generated by Django 5.1.1 on 2024-09-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_whychooseussection_advantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.FileField(upload_to='advantage_images/', verbose_name='Изображение преимущества'),
        ),
    ]
