# Generated by Django 5.1.1 on 2024-09-30 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_alter_advantage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статистики')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('icon', models.ImageField(upload_to='statistics_icons/', verbose_name='Иконка')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='service.statisticssection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
