# Generated by Django 5.1.1 on 2024-09-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_statisticssection_statisticitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticitem',
            name='icon',
            field=models.FileField(upload_to='statistics_icons/', verbose_name='Иконка'),
        ),
    ]
