# Generated by Django 5.1.1 on 2024-09-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_alter_statisticitem_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticitem',
            name='unit',
        ),
    ]
