# Generated by Django 5.1.1 on 2024-09-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_remove_statisticitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticitem',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
    ]
