# Generated by Django 5.1.1 on 2024-09-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_alter_statisticitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticitem',
            name='value',
            field=models.IntegerField(verbose_name='Значение'),
        ),
    ]
