# Generated by Django 5.1.1 on 2024-09-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_faqsection_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyCustomersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': "Секция 'Наши счастливые клиенты'",
                'verbose_name_plural': "Секция 'Наши счастливые клиенты'",
            },
        ),
        migrations.CreateModel(
            name='HappyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='customer_images/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='customer_videos/', verbose_name='Видео')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='service.happycustomerssection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Счастливый клиент',
                'verbose_name_plural': 'Счастливые клиенты',
            },
        ),
    ]
