# Generated by Django 5.1.1 on 2024-09-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_happycustomerssection_happycustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': "Секция 'Блог'",
                'verbose_name_plural': "Секция 'Блог'",
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст поста')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog_videos/', verbose_name='Видео')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/', verbose_name='Изображение превью')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='service.blogsection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Блог пост',
                'verbose_name_plural': 'Блог посты',
            },
        ),
    ]
