# Generated by Django 5.1.1 on 2024-09-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_blogsection_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='video_thumbnail',
        ),
    ]
