# Generated by Django 5.1.1 on 2024-09-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0037_remove_blogpost_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(verbose_name='Текст о компании')),
                ('logo', models.ImageField(upload_to='footer/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Футер секция',
                'verbose_name_plural': 'Футер секция',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('map_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на карту')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='service.footersection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='footer/payment/', verbose_name='Иконка метода оплаты')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='service.footersection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название соц. сети')),
                ('url', models.URLField(verbose_name='Ссылка на соц. сеть')),
                ('icon', models.ImageField(upload_to='footer/socials/', verbose_name='Иконка соц. сети')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='service.footersection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='День')),
                ('open_time', models.TimeField(verbose_name='Время открытия')),
                ('close_time', models.TimeField(verbose_name='Время закрытия')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выходной')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='service.footersection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Рабочее время',
                'verbose_name_plural': 'Рабочее время',
            },
        ),
    ]
