# Generated by Django 5.1.1 on 2024-09-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_footersection_contactinfofooter_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='logo',
            field=models.FileField(upload_to='footer/', verbose_name='Логотип'),
        ),
    ]
