# Generated by Django 5.1.1 on 2024-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0039_alter_footersection_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfofooter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
