# Generated by Django 5.1.1 on 2024-09-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0040_contactinfofooter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfofooter',
            name='map_url',
        ),
        migrations.AddField(
            model_name='contactinfofooter',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='Вставьте iframe код для карты', null=True, verbose_name='Google Maps iframe код'),
        ),
    ]
