# Generated by Django 5.1.1 on 2024-09-30 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0041_remove_contactinfofooter_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='title_address',
            field=models.CharField(blank=True, null=True, verbose_name="Заголовок 'Адрес'"),
        ),
        migrations.CreateModel(
            name='EmailInfoFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Email')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='service.footersection', verbose_name='Секция')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationInfoFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Адрес')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='service.footersection', verbose_name='Секция')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInfoFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Whats App')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='service.footersection', verbose_name='Секция')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ContactInfoFooter',
        ),
    ]
