# Generated by Django 5.1.1 on 2024-09-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0042_footersection_title_address_emailinfofooter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailinfofooter',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='footer/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='locationinfofooter',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='footer/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='phoneinfofooter',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='footer/', verbose_name='Логотип'),
        ),
    ]
