# Generated by Django 5.1.1 on 2024-09-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0043_emailinfofooter_logo_locationinfofooter_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.FileField(upload_to='footer/socials/', verbose_name='Иконка соц. сети'),
        ),
    ]
