# Generated by Django 5.1.1 on 2024-09-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0045_footersection_title_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='close_time',
            field=models.CharField(max_length=20, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='workhour',
            name='open_time',
            field=models.CharField(max_length=20, verbose_name='Время открытия'),
        ),
    ]
