# Generated by Django 5.1.1 on 2024-09-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0046_alter_workhour_close_time_alter_workhour_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.FileField(upload_to='footer/payment/', verbose_name='Иконка метода оплаты'),
        ),
    ]
