# Generated by Django 5.1.1 on 2024-09-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0047_alter_paymentmethod_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationinfofooter',
            name='map_iframe',
            field=models.TextField(blank=True, null=True, verbose_name='Iframe код для карты'),
        ),
    ]
