# Generated by Django 5.1.1 on 2024-09-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0048_locationinfofooter_map_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='best_in_town_text_en',
            field=models.CharField(blank=True, help_text='Текст вроде "Best in town Computer and Mobile Phone Repair Shop"', max_length=255, null=True, verbose_name='Лучший в городе текст'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='best_in_town_text_ru',
            field=models.CharField(blank=True, help_text='Текст вроде "Best in town Computer and Mobile Phone Repair Shop"', max_length=255, null=True, verbose_name='Лучший в городе текст'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='call_text_en',
            field=models.CharField(blank=True, default='Call Now', max_length=100, null=True, verbose_name='Текст для Call кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='call_text_ru',
            field=models.CharField(blank=True, default='Call Now', max_length=100, null=True, verbose_name='Текст для Call кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='rating_text_en',
            field=models.CharField(blank=True, help_text='Например, "Rated 4.9 with 34 reviews"', max_length=255, null=True, verbose_name='Текст рейтинга'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='rating_text_ru',
            field=models.CharField(blank=True, help_text='Например, "Rated 4.9 with 34 reviews"', max_length=255, null=True, verbose_name='Текст рейтинга'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle1_en',
            field=models.CharField(blank=True, help_text='Первый подзаголовок, например, "Premium out-of-warranty Apple Service Center in Dubai"', max_length=255, null=True, verbose_name='Подзаголовок 1'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle1_ru',
            field=models.CharField(blank=True, help_text='Первый подзаголовок, например, "Premium out-of-warranty Apple Service Center in Dubai"', max_length=255, null=True, verbose_name='Подзаголовок 1'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle2_en',
            field=models.CharField(blank=True, help_text='Второй подзаголовок, например, "Visit our service center to avail repair services..."', max_length=255, null=True, verbose_name='Подзаголовок 2'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle2_ru',
            field=models.CharField(blank=True, help_text='Второй подзаголовок, например, "Visit our service center to avail repair services..."', max_length=255, null=True, verbose_name='Подзаголовок 2'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, help_text='Основной заголовок для слайда, например, "Professional Repair Services..."', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Основной заголовок для слайда, например, "Professional Repair Services..."', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='whatsapp_text_en',
            field=models.CharField(blank=True, default='WhatsApp Now', max_length=100, null=True, verbose_name='Текст для WhatsApp кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='whatsapp_text_ru',
            field=models.CharField(blank=True, default='WhatsApp Now', max_length=100, null=True, verbose_name='Текст для WhatsApp кнопки'),
        ),
    ]
