# Generated by Django 5.1.1 on 2024-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0049_heroslide_best_in_town_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantageicontext',
            name='text_en',
            field=models.CharField(help_text='Текст преимущества, например, "Professional team"', max_length=255, null=True, verbose_name='Текст преимущества'),
        ),
        migrations.AddField(
            model_name='advantageicontext',
            name='text_ru',
            field=models.CharField(help_text='Текст преимущества, например, "Professional team"', max_length=255, null=True, verbose_name='Текст преимущества'),
        ),
    ]
