# Generated by Django 5.1.1 on 2024-09-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0050_advantageicontext_text_en_advantageicontext_text_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuressection',
            name='title_en',
            field=models.CharField(help_text='Заголовок, который отображается над сеткой с изображениями', max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='featuressection',
            name='title_ru',
            field=models.CharField(help_text='Заголовок, который отображается над сеткой с изображениями', max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='call_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст для Call кнопки'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='call_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст для Call кнопки'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='call_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст для Call кнопки'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='whatsapp_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст для WhatsApp кнопки'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='whatsapp_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст для WhatsApp кнопки'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='whatsapp_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст для WhatsApp кнопки'),
        ),
    ]
