# Generated by Django 5.1.1 on 2024-09-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0051_featuressection_title_en_featuressection_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureitem',
            name='title_en',
            field=models.CharField(help_text='Название, отображаемое под изображением', max_length=100, null=True, verbose_name='Название элемента'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='title_ru',
            field=models.CharField(help_text='Название, отображаемое под изображением', max_length=100, null=True, verbose_name='Название элемента'),
        ),
    ]
