# Generated by Django 5.1.1 on 2024-09-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0052_featureitem_title_en_featureitem_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок услуги'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок услуги'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='servicetab',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок таба'),
        ),
        migrations.AddField(
            model_name='servicetab',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок таба'),
        ),
    ]
