# Generated by Django 5.1.1 on 2024-09-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0053_serviceitem_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersection',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание баннера'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание баннера'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера'),
        ),
    ]
