# Generated by Django 5.1.1 on 2024-09-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0054_bannersection_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание преимущества'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание преимущества'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок преимущества'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок преимущества'),
        ),
        migrations.AddField(
            model_name='whychooseussection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='whychooseussection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
    ]
