# Generated by Django 5.1.1 on 2024-09-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0055_advantage_description_en_advantage_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название статистики'),
        ),
        migrations.AddField(
            model_name='statisticitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название статистики'),
        ),
        migrations.AddField(
            model_name='statisticssection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='statisticssection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
    ]
