# Generated by Django 5.1.1 on 2024-09-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0056_statisticitem_title_en_statisticitem_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faqsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='faqsection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
    ]
