# Generated by Django 5.1.1 on 2024-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0057_faqitem_answer_en_faqitem_answer_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Текст поста'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Текст поста'),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='footersection',
            name='about_text_en',
            field=models.TextField(null=True, verbose_name='Текст о компании'),
        ),
        migrations.AddField(
            model_name='footersection',
            name='about_text_ru',
            field=models.TextField(null=True, verbose_name='Текст о компании'),
        ),
        migrations.AddField(
            model_name='footersection',
            name='title_address_en',
            field=models.CharField(blank=True, null=True, verbose_name="Заголовок 'Адрес'"),
        ),
        migrations.AddField(
            model_name='footersection',
            name='title_address_ru',
            field=models.CharField(blank=True, null=True, verbose_name="Заголовок 'Адрес'"),
        ),
        migrations.AddField(
            model_name='footersection',
            name='title_work_time_en',
            field=models.CharField(blank=True, null=True, verbose_name="Заголовок 'Время работы'"),
        ),
        migrations.AddField(
            model_name='footersection',
            name='title_work_time_ru',
            field=models.CharField(blank=True, null=True, verbose_name="Заголовок 'Время работы'"),
        ),
        migrations.AddField(
            model_name='happycustomerssection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='happycustomerssection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='locationinfofooter',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='locationinfofooter',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='workhour',
            name='day_en',
            field=models.CharField(max_length=20, null=True, verbose_name='День'),
        ),
        migrations.AddField(
            model_name='workhour',
            name='day_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='День'),
        ),
    ]
