# Generated by Django 5.1.1 on 2024-10-01 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0058_blogpost_content_en_blogpost_content_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': 'О нас: Секция',
                'verbose_name_plural': 'О нас: Секция',
            },
        ),
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Описание')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Отображение текста справа')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='service.aboutsection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'О нас: Блок',
                'verbose_name_plural': 'О нас: Блоки',
            },
        ),
    ]
