# Generated by Django 5.1.1 on 2024-10-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0059_aboutsection_aboutblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutblock',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
    ]
