# Generated by Django 5.1.1 on 2024-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0060_aboutblock_text_en_aboutblock_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutblock',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='Отображение текста слева'),
        ),
    ]
