# Generated by Django 5.1.1 on 2024-10-01 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0061_alter_aboutblock_is_reversed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок секции')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': "Секция 'Наша команда'",
                'verbose_name_plural': "Секция 'Наша команда'",
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='team_images/', verbose_name='Фотография')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='service.teamsection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
    ]
