# Generated by Django 5.1.1 on 2024-10-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0062_teamsection_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/', verbose_name='Изображение'),
        ),
    ]
