# Generated by Django 5.1.1 on 2024-10-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0063_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
