# Generated by Django 5.1.1 on 2024-10-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0064_remove_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='URL аватара')),
            ],
            options={
                'verbose_name': 'Отзыв Google',
                'verbose_name_plural': 'Отзывы Google',
            },
        ),
    ]
