# Generated by Django 5.1.1 on 2024-10-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0065_googlereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': "Секция 'Google отзыв'",
                'verbose_name_plural': "Секция 'Google отзывы'",
            },
        ),
        migrations.AddField(
            model_name='googlereview',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google', to='service.teamsection', verbose_name='Секция'),
        ),
    ]
