# Generated by Django 5.1.1 on 2024-10-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0066_googlesection_googlereview_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlereview',
            name='section',
        ),
        migrations.DeleteModel(
            name='GoogleSection',
        ),
        migrations.DeleteModel(
            name='GoogleReview',
        ),
    ]
