# Generated by Django 5.1.1 on 2024-10-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0067_remove_googlereview_section_delete_googlesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': "Секция 'Google отзыв'",
                'verbose_name_plural': "Секция 'Google отзывы'",
            },
        ),
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='URL аватара')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google', to='service.teamsection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Отзыв Google',
                'verbose_name_plural': 'Отзывы Google',
            },
        ),
    ]
