# Generated by Django 5.1.1 on 2024-10-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0068_googlesection_googlereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereview',
            name='reviewer_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='reviewer_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='googlesection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='googlesection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
    ]
