# Generated by Django 5.1.1 on 2024-10-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0069_googlereview_reviewer_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlereview',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google', to='service.googlesection', verbose_name='Секция'),
        ),
    ]
