# Generated by Django 5.1.1 on 2024-10-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0070_alter_googlereview_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlereview',
            name='reviewer_name_en',
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='reviewer_name_ru',
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='text_ru',
        ),
    ]
