# Generated by Django 5.1.1 on 2024-10-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0072_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': "Раздел 'О нас'", 'verbose_name_plural': "Раздел 'О нас'"},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'verbose_name': "Раздел 'Блог'", 'verbose_name_plural': "Раздел 'Блог'"},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'verbose_name': 'Раздел Футер', 'verbose_name_plural': 'Раздел Футеры'},
        ),
        migrations.AlterModelOptions(
            name='googlesection',
            options={'verbose_name': "Раздел 'Google отзыв'", 'verbose_name_plural': "Раздел 'Google отзывы'"},
        ),
        migrations.AlterModelOptions(
            name='happycustomerssection',
            options={'verbose_name': "Раздел 'Наши счастливые клиенты'", 'verbose_name_plural': "Раздел 'Наши счастливые клиенты'"},
        ),
        migrations.AlterModelOptions(
            name='teamsection',
            options={'verbose_name': "Раздел 'Наша команда'", 'verbose_name_plural': "Раздел 'Наша команда'"},
        ),
        migrations.AlterModelOptions(
            name='whychooseussection',
            options={'verbose_name': "Раздел 'Почему стоит выбрать нас?'", 'verbose_name_plural': "Раздел 'Почему стоит выбрать нас?'"},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_bottom_logo',
            field=models.FileField(blank=True, null=True, upload_to='site_logos', verbose_name='Логотип нижней части сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default=1, verbose_name='Описание сайта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.FileField(blank=True, null=True, upload_to='site_favicons', verbose_name='Иконка сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.FileField(blank=True, null=True, upload_to='site_logos', verbose_name='Логотип сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название сайта'),
            preserve_default=False,
        ),
    ]
