# Generated by Django 5.1.1 on 2024-10-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0073_alter_aboutsection_options_alter_blogsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='call',
            field=models.FileField(default=1, upload_to='footer/', verbose_name='Логотип для звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersection',
            name='whatsapp',
            field=models.FileField(default=1, upload_to='footer/', verbose_name='Логотип для whatsapp'),
            preserve_default=False,
        ),
    ]
