# Generated by Django 5.1.1 on 2024-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0074_footersection_call_footersection_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhour',
            options={'ordering': ['id'], 'verbose_name': 'Рабочее время', 'verbose_name_plural': 'Рабочее время'},
        ),
        migrations.AlterField(
            model_name='workhour',
            name='day',
            field=models.CharField(max_length=20, null=True, verbose_name='День'),
        ),
    ]
