# Generated by Django 5.1.1 on 2024-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0075_alter_workhour_options_alter_workhour_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='day',
            field=models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='workhour',
            name='day_en',
            field=models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='workhour',
            name='day_ru',
            field=models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='День'),
        ),
    ]
