# Generated by Django 5.1.1 on 2024-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0077_remove_workhour_day_en_remove_workhour_day_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='День'),
        ),
    ]
