# Generated by Django 5.1.1 on 2024-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0078_alter_workhour_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhour',
            name='weekend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выходные, Праздники'),
        ),
        migrations.AddField(
            model_name='workhour',
            name='weekend_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выходные, Праздники'),
        ),
        migrations.AddField(
            model_name='workhour',
            name='weekend_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выходные, Праздники'),
        ),
    ]
